import type { Metadata } from "next";

import { Providers } from "../providers";
import Header from "../components/header";
import Abovefooter from "../components/above-footer";
import Footer from "../components/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<Providers>
			<Header />
			{children}
			<Abovefooter />
			<Footer />
		</Providers>
	);
}
