// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcupunctureInitialVisit = {
	cc: string;
	subjective: string;
	medications: Array<string>;
	allergies: Array<string>;
	objective: string;
	tcm_exam: string;
	assessment: string;
	plan: string;
	treatment: string;
};
