// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergiesState } from "./AllergiesState";
import type { MedicationsState } from "./MedicationsState";

export type AcupunctureFollowUpState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	chief_complaint: string;
	medications: MedicationsState;
	allergies: AllergiesState;
	subjective: string;
	objective: string;
	tcm_exam: string;
	assesment: string;
	plan: string;
	treatment: string;
	is_deleted: boolean;
};
