// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type AcupunctureFollowUpAdd = {
	patient_id: string;
	chief_complaint: string;
	medications_id: Array<string>;
	allergies_id: Array<string>;
	subjective: string;
	objective: string;
	last_updated_input: LastUpdatedInput;
	tcm_exam: string;
	assesment: string;
	plan: string;
	treatment: string;
	note_state: CurrentNoteState;
};
