// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergiesState } from "./AllergiesState";
import type { MedicationsState } from "./MedicationsState";

export type AcupunctureFollowUp = {
	chief_complaint: string;
	subjective: string;
	medications: Array<MedicationsState>;
	allergies: Array<AllergiesState>;
	objective: string;
	tcm_exam: string;
	assessment: string;
	plan: string;
	treatment: string;
};
