// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddressInput = {
	pin_code: string;
	city: string;
	state: string;
	address_line: string;
	country: string;
};
