// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdministerAdd } from "./AdministerAdd";

export type AdministerUpdate = { id: string; input: AdministerAdd };
