// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Brand } from "./Brand";
import type { DoctorType } from "./DoctorType";
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { Types } from "./Types";

export type AdministerAdd = {
	patient_id: string;
	vaccine: string;
	types: Types;
	brand: Brand;
	generic: string;
	ordered: string;
	recorded: string;
	dose: string;
	site: string;
	number_of_serial: number;
	lot: number;
	expiration: string;
	consent_obtain: string;
	administrated_by: string;
	clinic_location: string;
	provider: DoctorType;
	vis_date: string;
	vfs_financial_class: string;
	comments: string;
	last_updated_input: LastUpdatedInput;
};
