// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergySeveritiesType } from "./AllergySeveritiesType";
import type { Status } from "./Status";

export type AllergiesState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	allergen: string;
	reaction: string;
	allergy_severities: AllergySeveritiesType;
	input_date: string;
	comments: string;
	stauts: Status;
	is_deleted: boolean;
};
