// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergySeveritiesType } from "./AllergySeveritiesType";
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { Status } from "./Status";

export type AllergyAdd = {
	patient_id: string;
	allergen: string;
	reaction: string;
	allergy_severities: AllergySeveritiesType;
	input_date: string;
	status: Status;
	comments: string;
	last_updated_input: LastUpdatedInput;
};
