// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergyAdd } from "./AllergyAdd";

export type AllergyUpdate = { id: string; input: AllergyAdd };
