// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type AmendmentAdd = {
	patient_id: string;
	last_updated_input: LastUpdatedInput;
	source_of_request: string;
	request_details: string;
	decision: string;
	note_state: CurrentNoteState;
};
