// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Amendment = {
	source_of_request: string;
	request_details: string;
	decision: string;
};
