// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmendmentAdd } from "./AmendmentAdd";

export type AmendmentUpadte = { id: string; input: AmendmentAdd };
