// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppointmentAdd } from "./AppointmentAdd";

export type AppointmentUpdate = { id: string; appointment: AppointmentAdd };
