// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChooseAppointmentType } from "./ChooseAppointmentType";
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { VisitType } from "./VisitType";

export type AppointmentAdd = {
	patient_id: string;
	doctor_id: string;
	doctor_name: string | null;
	patient_name: string;
	visit: VisitType;
	date: string;
	appointment_duration: number;
	choose_appointment: ChooseAppointmentType;
	note: string;
	room_and_equipment_no: string;
	staff_id: string;
	staff_name: string;
	last_updated_input: LastUpdatedInput;
};
