// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChooseAppointmentType } from "./ChooseAppointmentType";
import type { VisitType } from "./VisitType";

export type AppointmentState = {
	id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	org_id: string;
	patient_id: string;
	doctor_id: string;
	service_location_id: string;
	doctor_name: string | null;
	patient_name: string;
	visit: VisitType;
	date: string;
	appointment_duration: number;
	choose_appointment: ChooseAppointmentType;
	note: string;
	room_and_equipment_no: string;
	staff_id: string;
	staff_name: string;
	is_deleted: boolean;
};
