// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthenticatedUser = {
	id: string;
	token: string;
	selected_language: string;
	role: Array<string>;
	user_name: string;
	org_id: string;
	org_name: string;
	service_location_id: string;
};
