// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthUser = {
	first_name: string;
	middle_name: string | null;
	last_name: string;
	email: string;
	photo_url: string;
	gender: string;
	date_of_birth: string;
	password_hash: string;
};
