// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Clients = {
	name: string;
	address: string;
	mobile_number: string;
	email: string;
	gst_no: string;
	pan_no: string;
};
