// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CombinedRecord = {
	brand: string;
	generic: string;
	details: string;
	category: string;
	side_effects: string;
	drug_dose_info: string;
	precautions: string;
	manufacturer_name: string;
	medicines: string;
	contra_indications: string;
	diseases: string;
	interactions: string;
	contains: string;
};
