// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Consultation = {
	cc: string;
	hpi: string;
	pmhx: Array<string>;
	pshx: Array<string>;
	fhx: Array<string>;
	soc_hx: Array<string>;
	ob_preg_hx: Array<string>;
	hospitalizations: Array<string>;
	implantable_devices: Array<string>;
	ros: string;
	medications: Array<string>;
	allergies: Array<string>;
	mental_functional: string;
	vitals: string;
	exam: string;
	assessment: string;
	plan: string;
	minor_procedures: string;
	goals: string;
	health_concerns: string;
};
