// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhoneNoTypeForContact } from "./PhoneNoTypeForContact";

export type Contact = { number: string; number_type: PhoneNoTypeForContact };
