// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DoctorDetails = {
	Id: bigint;
	DoctorName: string;
	Speciality: string;
	Experience: string;
	HospitalAddress: string;
	City: string;
	Pincode: bigint;
};
