// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorType } from "./DoctorType";
import type { UserState } from "./UserState";

export type DoctorState = {
	id: string;
	user: UserState;
	org_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	doctor_role: Array<DoctorType>;
	doctor_register_number: string;
	doctor_department: string;
	doctor_speciality: string;
	emergency: boolean;
	is_deleted: boolean;
};
