// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorType } from "./DoctorType";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type DoctorAdd = {
	user_id: string;
	doctor_role: Array<DoctorType>;
	docter_register_number: string;
	doctor_department: string;
	doctor_speciality: string;
	emergency: boolean;
	last_updated_input: LastUpdatedInput;
};
