// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Doctors = {
	doctor_name: string;
	speciality: string;
	experience: string;
	hospital_address: string;
	city: string;
	pincode: string;
};
