// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStauts } from "./HealthStauts";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type FamilyHistoryAdd = {
	patient_id: string;
	family_member: string;
	health_status: HealthStauts;
	general: Array<string> | null;
	cancer: Array<string> | null;
	comments: Array<string> | null;
	last_updated_input: LastUpdatedInput;
};
