// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthStauts } from "./HealthStauts";

export type FamilyHistoryState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	family_member: string;
	health_status: HealthStauts;
	general: Array<string> | null;
	cancer: Array<string> | null;
	comments: Array<string> | null;
	is_deleted: boolean;
};
