// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FamilyHistoryAdd } from "./FamilyHistoryAdd";

export type FamilyHistoryUpdate = { id: string; input: FamilyHistoryAdd };
