// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Getorganization = {
	id: string;
	name: string;
	details: string;
	mobile_number: string;
	email: string;
	pin_code: string;
	city: string;
	state: string;
	address_line: string;
	country: string;
};
