// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetServiceLocation = {
	id: string;
	org_id: string;
	org_name: string;
	service_location_name: string;
	pin_code: string;
	city: string;
	state: string;
	address_line: string;
	country: string;
};
