// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderType } from "./GenderType";
import type { GovIdType } from "./GovIdType";
import type { PhoneNoTypeForContact } from "./PhoneNoTypeForContact";

export type GetSystemadmin = {
	id: string;
	org_id: string;
	first_name: string;
	middle_name: string;
	last_name: string;
	dob: string;
	email: string;
	gender: GenderType;
	photo_url: string;
	pin_code: string;
	city: string;
	state: string;
	address_line: string;
	country: string;
	number: string;
	number_type: PhoneNoTypeForContact;
	id_no: string;
	id_type: GovIdType;
};
