// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetUsers = {
	id: string;
	mobile_number: string;
	role: string;
	is_deleted: boolean;
};
