// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GovIdType } from "./GovIdType";

export type GovInfoInput = { id_no: string; id_type: GovIdType };
