// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Group = {
	group_session_content: string;
	session_details: string;
	individual_behavior_during_session: string;
	dsm_5: string;
	assessment: string;
	plan: string;
};
