// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type GroupAdd = {
	patient_id: string;
	last_updated_input: LastUpdatedInput;
	group_session_content: string;
	session_details: string;
	individual_behavior_during_session: string;
	dsm_5: string;
	assesment: string;
	plan: string;
	note_state: CurrentNoteState;
};
