// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GroupAdd } from "./GroupAdd";

export type GroupUpadte = { id: string; input: GroupAdd };
