// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GroupState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	is_deleted: boolean;
	group_session_content: string;
	session_details: string;
	individual_behavior_during_session: string;
	dsm_5: string;
	assesment: string;
	plan: string;
};
