// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergiesState } from "./AllergiesState";
import type { MedicationsState } from "./MedicationsState";
import type { VitalsState } from "./VitalsState";

export type HistoryAndPhysical = {
	chief_complaint: string;
	history_of_present_illness: string;
	past_medical_history: string;
	past_surgical_history: string;
	family_history: string;
	social_history: string;
	obstetric_and_pregnancy_history: string;
	hospitalizations: string;
	implantable_devices: string;
	review_of_systems: string;
	medications: Array<MedicationsState>;
	allergies: Array<AllergiesState>;
	mental_or_functional: string;
	vitals: VitalsState;
	exam: string;
	assessment: string;
	plan: string;
	minor_procedures: string;
	goals: string;
	health_concerns: string;
};
