// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorType } from "./DoctorType";

export type HistoricalState = {
	id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	org_id: string;
	patient_id: string;
	vaccine: string;
	types: string;
	date: string;
	number_in_series: string;
	provider: DoctorType;
	source_of_information: string;
	comments: string;
	is_deleted: boolean;
};
