// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryAndPhysicalAdd } from "./HistoryAndPhysicalAdd";

export type HistoryAndPhysicalUpdate = {
	id: string;
	input: HistoryAndPhysicalAdd;
};
