// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DoctorType } from "./DoctorType";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type HistoricalAdd = {
	patient_id: string;
	vaccine: string;
	types: string;
	date: string;
	number_in_series: string;
	provider: DoctorType;
	source_of_information: string;
	comments: string;
	last_updated_input: LastUpdatedInput;
};
