// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type HistoryAndPhysicalAdd = {
	patient_id: string;
	chief_complaint: string;
	history_of_present_illness: string;
	past_medical_history: string;
	past_surgical_history: string;
	family_history: string;
	social_history: string;
	obstetric_and_pregnancy_history: string;
	hospitalizations: string;
	implantable_devices: string;
	review_of_systems: string;
	medications_id: Array<string>;
	allergies_id: Array<string>;
	mental_or_functional: string;
	vitals_id: string;
	exam: string;
	assessment: string;
	plan: string;
	minor_procedures: string;
	goals: string;
	health_concerns: string;
	note_state: CurrentNoteState;
	last_updated_input: LastUpdatedInput;
};
