// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoricalAdd } from "./HistoricalAdd";

export type HistoricalUpdate = { id: string; input: HistoricalAdd };
