// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type HospitalizationAdd = {
	patient_id: string;
	admission_date: string;
	related_to: string | null;
	status: string | null;
	length_of_stay: number | null;
	procedure: string | null;
	comments: string | null;
	last_updated_input: LastUpdatedInput;
};
