// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HospitalizationState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	admission_date: string;
	related_to: string | null;
	status: string | null;
	length_of_stay: number | null;
	procedure: string | null;
	comments: string | null;
	is_deleted: boolean;
};
