// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ICD10 = {
	code: string;
	category: string | null;
	icd_code: string;
	description: string;
	long_description: string;
	id: bigint;
};
