// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Icd10Record = {
	disease_code: string;
	disease_subtype: string;
	disease_subcode: string;
	disease_name: string;
	disease_description: string;
	disease_category: string;
};
