// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type ImplantableDevicesAdd = {
	patient_id: string;
	status: string | null;
	udi: string | null;
	udi_unknown: boolean | null;
	comments: string | null;
	last_updated_input: LastUpdatedInput;
};
