// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImplantableDevicesAdd } from "./ImplantableDevicesAdd";

export type ImplantableDevicesUpdate = {
	id: string;
	input: ImplantableDevicesAdd;
};
