// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImplantableDevicesState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	status: string | null;
	udi: string | null;
	udi_unknown: boolean | null;
	comments: string | null;
	is_deleted: boolean;
};
