// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LastUpdatedInput = {
	system_admin: string;
	doctors: string;
	patients: string;
	appointments: string;
	prescription: string;
	service_location: string;
	add_historical: string;
	administer: string;
	allergy: string;
	medication: string;
	not_administer: string;
	order: string;
	problems: string;
	vitals: string;
	familyhistory: string;
	hospitalization: string;
	implantabledevices: string;
	obandpregnanacy: string;
	pastmedicalhistory: string;
	pastsurgicalhistory: string;
	socialhistory: string;
	staff: string;
	note: string;
	user: string;
	organization: string;
};
