// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocationRecord = {
	pin_code: string;
	city_name: string;
	district: string;
	state_name: string;
	country_name: string;
};
