// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { Status } from "./Status";

export type MedicationsAdd = {
	patient_id: string;
	status: Status;
	drug: string;
	instruction: string | null;
	comments: string;
	last_updated_input: LastUpdatedInput;
};
