// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type MedSpaProcedureAdd = {
	patient_id: string;
	last_updated_input: LastUpdatedInput;
	procedure: string;
	performed_by: string;
	indication: string;
	comments: string;
	note_state: CurrentNoteState;
};
