// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotAdministeredAdd } from "./NotAdministeredAdd";

export type NotAdministeredUpdate = { id: string; input: NotAdministeredAdd };
