// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcupunctureFollowUp } from "./AcupunctureFollowUp";
import type { AcupunctureInitialVisit } from "./AcupunctureInitialVisit";
import type { AcupunctureReassessment } from "./AcupunctureReassessment";
import type { Amendment } from "./Amendment";
import type { Consultation } from "./Consultation";
import type { DischargeSummary } from "./DischargeSummary";
import type { Group } from "./Group";
import type { HistoryAndPhysical } from "./HistoryAndPhysical";
import type { MedSpaIVProcedure } from "./MedSpaIVProcedure";
import type { MedSpaProcedure } from "./MedSpaProcedure";
import type { MemoToRecord } from "./MemoToRecord";
import type { NurseVisit } from "./NurseVisit";
import type { OBEvaluation } from "./OBEvaluation";
import type { OfficeForm } from "./OfficeForm";
import type { Phone } from "./Phone";
import type { PhysicalTherapyDischargeSummary } from "./PhysicalTherapyDischargeSummary";
import type { PhysicalTherapyInitialEvaluation } from "./PhysicalTherapyInitialEvaluation";
import type { PhysicalTherapyInterim } from "./PhysicalTherapyInterim";
import type { PhysicalTherapyProgress } from "./PhysicalTherapyProgress";
import type { Procedure } from "./Procedure";
import type { PsychInitialVisit } from "./PsychInitialVisit";
import type { PsychProgress } from "./PsychProgress";
import type { SOAPNote } from "./SOAPNote";
import type { SpeechAndLanguageInitialEvaluation } from "./SpeechAndLanguageInitialEvaluation";
import type { SpeechAndLanguageProgressReport } from "./SpeechAndLanguageProgressReport";
import type { SpeechAndLanguageTreatmentNote } from "./SpeechAndLanguageTreatmentNote";
import type { TelehealthHnP } from "./TelehealthHnP";
import type { TelehealthSOAP } from "./TelehealthSOAP";
import type { TherapistInitialVisit } from "./TherapistInitialVisit";
import type { TherapistProgress } from "./TherapistProgress";
import type { UrgentCare } from "./UrgentCare";

export type NoteType =
	| { HistoryAndPhysical: HistoryAndPhysical }
	| { SOAPNote: SOAPNote }
	| { AcupunctureFollowUp: AcupunctureFollowUp }
	| { AcupunctureInitialVisit: AcupunctureInitialVisit }
	| { AcupunctureReassessment: AcupunctureReassessment }
	| { Amendment: Amendment }
	| { Consultation: Consultation }
	| { DischargeSummary: DischargeSummary }
	| { Group: Group }
	| { MedSpaIVProcedure: MedSpaIVProcedure }
	| { MedSpaProcedure: MedSpaProcedure }
	| { MemoToRecord: MemoToRecord }
	| { NurseVisit: NurseVisit }
	| { OBEvaluation: OBEvaluation }
	| { OfficeForm: OfficeForm }
	| { Phone: Phone }
	| { PhysicalTherapyDischargeSummary: PhysicalTherapyDischargeSummary }
	| { PhysicalTherapyInitialEvaluation: PhysicalTherapyInitialEvaluation }
	| { PhysicalTherapyInterim: PhysicalTherapyInterim }
	| { PhysicalTherapyProgress: PhysicalTherapyProgress }
	| { Procedure: Procedure }
	| { PsychInitialVisit: PsychInitialVisit }
	| { PsychProgress: PsychProgress }
	| { SpeechAndLanguageInitialEvaluation: SpeechAndLanguageInitialEvaluation }
	| { SpeechAndLanguageProgressReport: SpeechAndLanguageProgressReport }
	| { SpeechAndLanguageTreatmentNote: SpeechAndLanguageTreatmentNote }
	| { TelehealthHnP: TelehealthHnP }
	| { TelehealthSOAP: TelehealthSOAP }
	| { TherapistInitialVisit: TherapistInitialVisit }
	| { TherapistProgress: TherapistProgress }
	| { UrgentCare: UrgentCare };
