// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { NoteType } from "./NoteType";

export type NoteAdd = {
	patient_id: string;
	note: NoteType;
	note_state: CurrentNoteState;
	last_updated_input: LastUpdatedInput;
};
