// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NurseVisit = {
	hpi: string;
	pmhx: Array<string>;
	pshx: Array<string>;
	fhx: Array<string>;
	soc_hx: Array<string>;
	ob_preg_hx: Array<string>;
	hospitalizations: Array<string>;
	medications: Array<string>;
	allergies: Array<string>;
	vitals: string;
};
