// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type OBandPregnancyAdd = {
	patient_id: string;
	age_onset_of_menses: number;
	age_at_menopause: number;
	comments_ob: string | null;
	total_pregnancy: number | null;
	full_term: number | null;
	pre_term: number | null;
	miscarriages: number | null;
	living: number | null;
	comments_pregnancy: string | null;
	last_updated_input: LastUpdatedInput;
};
