// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OBandPregnancyAdd } from "./OBandPregnancyAdd";

export type OBandPregnancyUpdate = { id: string; input: OBandPregnancyAdd };
