// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OBandPregnancyState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	age_onset_of_menses: number;
	age_at_menopause: number;
	comments_ob: string | null;
	total_pregnancy: number | null;
	full_term: number | null;
	pre_term: number | null;
	miscarriages: number | null;
	living: number | null;
	comments_pregnancy: string | null;
	is_deleted: boolean;
};
