// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OBEvaluation = {
	cc: string;
	hpi: string;
	pmhx: Array<string>;
	pshx: Array<string>;
	fhx: Array<string>;
	soc_hx: Array<string>;
	ob_preg_hx: Array<string>;
	past_pregnancy_hx: string;
	hospitalizations: Array<string>;
	medications: Array<string>;
	allergies: Array<string>;
	mental_functional: string;
	vitals: string;
	exam: string;
	gestational_age: string;
	ob_exam: string;
	past_lab_hx: string;
	assessment: string;
	plan: string;
};
