// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type OfficeFormAdd = {
	patient_id: string;
	form: string;
	note_state: CurrentNoteState;
	last_updated_input: LastUpdatedInput;
};
