// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Types } from "./Types";

export type OrderState = {
	id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	org_id: string;
	patient_id: string;
	vaccine: string;
	types: Types;
	ordered: string;
	provider: string;
	comments: string;
	is_deleted: boolean;
};
