// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { Types } from "./Types";

export type OrderAdd = {
	patient_id: string;
	vaccine: string;
	types: Types;
	ordered: string;
	provider: string;
	comments: string;
	last_updated_input: LastUpdatedInput;
};
