// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderAdd } from "./OrderAdd";

export type OrderUpdate = { id: string; input: OrderAdd };
