// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";

export type OrganizationState = {
	id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	name: string;
	details: string;
	phone_number: string;
	email: string;
	address: AddressInput;
	is_deleted: boolean;
};
