// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";

export type OrgDetailsDto = {
	name: string;
	details: string;
	phone_number: string;
	email: string;
	address: AddressInput;
};
