// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgDetails } from "./OrgDetails";
import type { SystemAdminDetails } from "./SystemAdminDetails";

export type OrgUser = {
	org_details: OrgDetails;
	systemadmin_details: SystemAdminDetails;
};
