// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PastMedicalHistoryState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	blood_type: string | null;
	head: string | null;
	respiratory: string | null;
	musculoskeletal: string | null;
	endocrine: string | null;
	eyes: string | null;
	gastrointestinal: string | null;
	skin: string | null;
	ears: string | null;
	noses: string | null;
	neurological: string | null;
	heme: string | null;
	mouth: string | null;
	infectious: string | null;
	cardiovascular: string | null;
	genitourinary: string | null;
	psychiatric: string | null;
	comments: string | null;
	is_deleted: boolean;
};
