// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type PastSurgicalHistoryAdd = {
	patient_id: string;
	common_surgeries: Array<string> | null;
	comments: string | null;
	last_updated_input: LastUpdatedInput;
};
