// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type PastSurgicalHistoryDelete = {
	id: string;
	patient_id: string;
	last_updated_input: LastUpdatedInput;
};
