// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PastMedicalHistoryAdd } from "./PastMedicalHistoryAdd";

export type PastMedicalHistoryUpdate = {
	id: string;
	input: PastMedicalHistoryAdd;
};
