// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhoneAdd } from "./PhoneAdd";

export type PhoneUpdate = { id: string; input: PhoneAdd };
