// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhysicalTherapyProgress = {
	reason_for_referral: string;
	subjective: string;
	medications: Array<string>;
	vitals: string;
	objective: string;
	tests_and_measures: string;
	treatment: string;
	assessment: string;
	plan: string;
};
