// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type PrescriptionAdd = {
	patient_id: string;
	patient_name: string;
	presecription_name: string;
	instruction: string | null;
	date: string;
	drug_name: Array<string>;
	last_updated_input: LastUpdatedInput;
};
