// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrescriptionState = {
	id: string;
	org_id: string;
	patient_id: string;
	doctor_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	patient_name: string;
	presecription_name: string;
	instruction: string | null;
	date: string;
	drug_name: Array<string>;
	is_deleted: boolean;
};
