// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { ProblemTypes } from "./ProblemTypes";
import type { Status } from "./Status";

export type ProblemsAdd = {
	patient_id: string;
	status: Status;
	issue: string;
	icd_10_problem: string | null;
	issue_type: ProblemTypes;
	start_date: string;
	end_date: string;
	comment: string;
	last_updated_input: LastUpdatedInput;
};
