// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProblemTypes } from "./ProblemTypes";
import type { Status } from "./Status";

export type ProblemState = {
	id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	org_id: string;
	patient_id: string;
	status: Status;
	issue: string;
	icd_10_problem: string | null;
	issue_type: ProblemTypes;
	start_date: string;
	end_date: string;
	comment: string;
	is_deleted: boolean;
};
