// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Procedure = {
	procedure: string;
	performed_by: string;
	indication: string;
	comments: string;
};
