// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PsychProgress = {
	cc: string;
	psych_symptom_follow_up: string;
	psych_syndromes: string;
	medications: Array<string>;
	mse: string;
	psych_impression: string;
	dsm_5: string;
	psych_intervention: string;
	assessment: string;
	plan: string;
};
