// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PsychInitialVisit = {
	cc: string;
	hpi: string;
	psych_hx: string;
	pmhx: Array<string>;
	pshx: Array<string>;
	psychfhx: string;
	psychshx: string;
	medications: Array<string>;
	mse: string;
	tests: string;
	psych_impression: string;
	dsm_5: string;
	assessment: string;
	plan: string;
};
