// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type ServiceLocationAdd = {
	service_location_name: string;
	address: AddressInput;
	start_time: string;
	end_time: string;
	last_updated_input: LastUpdatedInput;
};
