// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";

export type ServiceLocationState = {
	id: string;
	org_id: string;
	service_location_name: string;
	start_time: string;
	end_time: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	address: AddressInput;
	is_deleted: boolean;
};
