// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SoapAdd } from "./SoapAdd";

export type SoapUpdate = { id: string; input: SoapAdd };
