// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentNoteState } from "./CurrentNoteState";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type SoapAdd = {
	patient_id: string;
	chief_complaint: string;
	subjective: string;
	medications_id: Array<string>;
	allergies_id: Array<string>;
	mental_or_functional: string;
	vitals_id: string;
	objective: string;
	assessment: string;
	plan: string;
	note_state: CurrentNoteState;
	last_updated_input: LastUpdatedInput;
};
