// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergiesState } from "./AllergiesState";
import type { MedicationsState } from "./MedicationsState";
import type { VitalsState } from "./VitalsState";

export type SOAPNoteState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	chief_complaint: string;
	subjective: string;
	medications: MedicationsState;
	allergies: AllergiesState;
	mental_or_functional: string;
	vitals: VitalsState;
	objective: string;
	assessment: string;
	plan: string;
	is_deleted: boolean;
};
