// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllergiesState } from "./AllergiesState";
import type { MedicationsState } from "./MedicationsState";
import type { VitalsState } from "./VitalsState";

export type SOAPNote = {
	chief_complaint: string;
	subjective: string;
	medications: Array<MedicationsState>;
	allergies: Array<AllergiesState>;
	mental_or_functional: string;
	vitals: VitalsState;
	objective: string;
	assessment: string;
	plan: string;
};
