// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderType } from "./GenderType";

export type SocialHistoryState = {
	id: string;
	org_id: string;
	patient_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	birth_gender: GenderType;
	tobacco: Array<string> | null;
	alcohol: Array<string> | null;
	cardiovascular: Array<string> | null;
	sexual_activity: Array<string> | null;
	drug_abuse: Array<string> | null;
	safety: Array<string> | null;
	comments: string | null;
	is_deleted: boolean;
};
