// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderType } from "./GenderType";
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type SocialHistoryAdd = {
	patient_id: string;
	birth_gender: GenderType;
	tobacco: Array<string> | null;
	alcohol: Array<string> | null;
	cardiovascular: Array<string> | null;
	sexual_activity: Array<string> | null;
	drug_abuse: Array<string> | null;
	safety: Array<string> | null;
	comments: string | null;
	last_updated_input: LastUpdatedInput;
};
