// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeechAndLanguageTreatmentNote = {
	cc: string;
	subjective: string;
	objective: string;
	assessment: string;
	plan: string;
	goals: string;
};
