// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeechAndLanguageProgressReport = {
	cc: string;
	subjective: string;
	current_goals: string;
	receptive_expressive_language: string;
	pragmatics: string;
	oral_mechanism_exam: string;
	articulation: string;
	fluency: string;
	voice: string;
	assessment: string;
	plan: string;
	goals: string;
};
