// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeechAndLanguageInitialEvaluation = {
	cc: string;
	history: string;
	speech_development: string;
	receptive_expressive_language: string;
	pragmatics: string;
	oral_mechanism_exam: string;
	articulation: string;
	fluency: string;
	voice: string;
	assessment: string;
	plan: string;
	goals: string;
};
