// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaffAdd } from "./StaffAdd";

export type StaffUpdate = { id: string; input: StaffAdd };
