// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { StaffType } from "./StaffType";

export type StaffAdd = {
	user_id: string;
	staff_department: Array<StaffType>;
	emergency: boolean;
	last_updated_input: LastUpdatedInput;
};
