// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StaffType } from "./StaffType";
import type { UserState } from "./UserState";

export type StaffState = {
	id: string;
	org_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	user: UserState;
	staff_department: Array<StaffType>;
	emergency: boolean;
	is_deleted: boolean;
};
