// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StaffType =
	| "Consultation"
	| "Examination"
	| "Diagnosis"
	| "Treatment"
	| "Procedure"
	| "Surgery"
	| "Therapy"
	| "Counseling"
	| "MedicationManagement"
	| "Imaging"
	| "LaboratoryTest"
	| "Rehabilitation"
	| "HomeCare"
	| "Telemedicine"
	| "WellnessProgram";
