// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactInput } from "./ContactInput";
import type { GovInfoInput } from "./GovInfoInput";
import type { SystemAdminRole } from "./DB\\SystemAdminRole";
import type { UserInput } from "./UserInput";

export type SystemAdminState = {
	id: string;
	org_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	user: UserInput;
	phone: ContactInput;
	government_info: GovInfoInput;
	roles: Array<SystemAdminRole>;
	password: string;
	is_deleted: boolean;
};
