// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SystemAdminAdd } from "./SystemAdminAdd";

export type SystemAdminUpdate = {
	id: string;
	org_id: string;
	input: SystemAdminAdd;
};
