// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactInput } from "./ContactInput";
import type { GovInfoInput } from "./GovInfoInput";
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { OrganizationAdd } from "./OrganizationAdd";
import type { SystemAdminRole } from "./DB\\SystemAdminRole";
import type { UserInput } from "./UserInput";

export type SystemAdminAdd = {
	org_details: OrganizationAdd;
	user: UserInput;
	roles: Array<SystemAdminRole>;
	phone: ContactInput;
	government_info: GovInfoInput;
	password: string;
	confirm_password: string;
	last_updated_input: LastUpdatedInput;
};
