// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TelehealthSOAP = {
	cc: string;
	subjective: string;
	medications: Array<string>;
	allergies: Array<string>;
	mental_functional: string;
	vitals: string;
	objective: string;
	assessment: string;
	plan: string;
};
