// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UrgentCare = {
	cc: string;
	hpi: string;
	pmhx: Array<string>;
	pshx: Array<string>;
	fhx: Array<string>;
	soc_hx: Array<string>;
	hospitalizations: Array<string>;
	ros: string;
	medications: Array<string>;
	allergies: Array<string>;
	vitals: string;
	exam: string;
	diagnostic_studies: string;
	medical_decision_making: string;
	assessment: string;
	plan: string;
	minor_procedures: string;
};
