// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";
import type { ContactInput } from "./ContactInput";
import type { GovInfoInput } from "./GovInfoInput";
import type { UserInput } from "./UserInput";

export type UserDetails = {
	user: UserInput;
	address: AddressInput;
	phone: ContactInput;
	government_info: GovInfoInput;
};
