// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenderType } from "./GenderType";

export type UserInput = {
	first_name: string;
	middle_name: string;
	last_name: string;
	dob: string;
	email: string;
	gender: GenderType;
	photo_url: string;
};
