// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleType } from "./RoleType";

export type Users = {
	mobile_number: string;
	password: string;
	role: Array<RoleType>;
};
