// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";
import type { ContactInput } from "./ContactInput";
import type { GovInfoInput } from "./GovInfoInput";
import type { LastUpdatedInput } from "./LastUpdatedInput";
import type { UserInput } from "./UserInput";

export type UserAdd = {
	user: UserInput;
	phone: ContactInput;
	address: AddressInput;
	goverment_info: GovInfoInput;
	password: string;
	confirm_password: string;
	last_updated_input: LastUpdatedInput;
};
