// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type UserPassword = {
	id: string;
	password: string;
	confirm_password: string;
	last_updated_input: LastUpdatedInput;
};
