// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VitalsState = {
	id: string;
	org_id: string;
	patient_id: string;
	doctor_id: string;
	created_by: string;
	updated_by: string;
	created_at: string;
	last_updated: string;
	date_time: string | null;
	blood_pressure: number | null;
	heart_rate: number | null;
	comments: string | null;
	height: number | null;
	weight: number | null;
	bmi: number | null;
	temperature: number | null;
	is_deleted: boolean;
};
