// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VitalsAdd } from "./VitalsAdd";

export type VitalsUpdate = { id: string; input: VitalsAdd };
