// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastUpdatedInput } from "./LastUpdatedInput";

export type VitalsAdd = {
	patient_id: string;
	date_time: string | null;
	blood_pressure: number | null;
	heart_rate: number | null;
	height: number | null;
	weight: number | null;
	temperature: number | null;
	bmi: number | null;
	comments: string | null;
	last_updated_input: LastUpdatedInput;
};
